### ISSUE TITLE
Ramp-up period option in parallel batch execution mode

### ISSUE THREAD

**Issue by aztheque** [gwen-interpreter/gwen#18]
Currently in parallel batch execution mode, all features start running simultaneously (up to a maximum number of processes determined by gwen). It is useful, especially when combined with CSV data driven features, to identify and diagnose potential threading issues in underlying applications.

However, there are some situations where it would be beneficial to stagger the start times of these parallel run features. Especially, in the case where gwen features are used to simulate load (or simply speed up running features) on the underlying application and the actions performed in each feature would not occur under normal circumstances. E.g., multiple near-simultaneous login with same credentials.

It would be great if there was an option to configure the "ramp-up period" when running features in parallel batch execution mode.

**Comment by bjuric** [comment]
@aztheque, we've implemented this in the pull request above and published a gwen-web snapshot for you here: 
https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/1.2.0-1-g3ae08b8-SNAPSHOT/gwen-web-1.2.0-1-g3ae08b8-SNAPSHOT.zip

See pull request #19 for details and configuration instructions. Let us know how it goes, and we'll then then merge it in and create a new release if you're happy with it.

**Comment by aztheque** [comment]
Thanks @bjuric works as expected :thumbsup:

**Comment by bjuric** [comment]
Excellent! Merging PR #19 and closing issue.
