### ISSUE TITLE
DSL to access feature file name and scenario name

### ISSUE THREAD

**Issue by anshu781126** [gwen-interpreter/gwen#36]
DSL to access feature file name and scenario name

**Comment by bjuric** [comment]
Thanks for raising this.  I'm thinking we can do this with some implicit attributes in Gwen named as follows:

- `gwen.feature.file.name`
   - The feature file name
- `gwen.feature.file.path`
   - The feature file path (as provided to Gwen on command line)
- `gwen.feature.file.absolutePath`
   - The absolute feature file path
- `gwen.feature.name`
   - The feature name (as specified in Feature clause)
- `gwen.scenario.name`
   - The current scenario name (as specified in Scenario clause)

The attributes can be referenced by name in any DSL and also `${interpolated}` (dereferenced) in any step.

In the case of the REPL, they'll be available if you launch Gwen with a feature file in REPL mode. But if not, then an error will be reported for any steps that reference these attributes.

Thoughts?

**Comment by bjuric** [comment]
Please try out the above using the snapshot build below and let us know how it goes. Thanks

Snapshot build:
- [gwen-web-2.11.1-13-gff8ce07-SNAPSHOT.zip](https://oss.sonatype.org/content/repositories/snapshots/org/gweninterpreter/gwen-web/2.11.1-13-gff8ce07-SNAPSHOT/gwen-web-2.11.1-13-gff8ce07-SNAPSHOT.zip)

**Comment by anshu781126** [comment]
All file variables are accessible in feature file.

**Comment by bjuric** [comment]
Released in gwen-web v[2.12.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.12.0)
