### ISSUE TITLE
Support for webdriver desired_capability in gwen.properties

### ISSUE THREAD

**Issue by Rahul9844** [gwen-interpreter/gwen#39]
There should be some mechanism/configuration to support & configure webdriver desired_capabilities.

Below links contains information on the same.
https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

**Comment by bjuric** [comment]
Please raise this in the gwen-web register (since it is web related) here https://github.com/gwen-interpreter/gwen-web. Then close this one. Thanks.

**Comment by Rahul9844** [comment]
I have moved this to gwen-web
https://github.com/gwen-interpreter/gwen-web/issues/43
