### ISSUE TITLE
Getting Error while creating the Junit-xml reports from Jenkins

### ISSUE THREAD

**Issue by DK-India** [gwen-interpreter/gwen#47]
Hi, i am getting an error when i try to create Junit , XML reports using following command.
./gwen features -b -f junit -Dgwen.web.browser.headless=true

`
14:20:22 ERROR - ip-10-0-1-100: ip-10-0-1-100: Name or service not known
14:20:22 java.net.UnknownHostException: ip-10-0-1-100: ip-10-0-1-100: Name or service not known
14:20:22 	at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
14:20:22 	at gwen.report.JUnitReportFormatter.formatDetail(JUnitReportFormatter.scala:59)
14:20:22 	at gwen.report.JUnitReportFormatter.formatDetail$(JUnitReportFormatter.scala:45)
14:20:22 	at gwen.report.JUnitReportGenerator.formatDetail(JUnitReportGenerator.scala:33)
14:20:22 	at gwen.report.ReportGenerator.reportFeatureDetail(ReportGenerator.scala:96)
14:20:22 	at gwen.report.ReportGenerator.reportDetail(ReportGenerator.scala:73)
14:20:22 	at gwen.eval.GwenLauncher.$anonfun$bindReportFiles$1(GwenLauncher.scala:192)
14:20:22 	at scala.collection.immutable.List.map(List.scala:282)
14:20:22 	at gwen.eval.GwenLauncher.bindReportFiles(GwenLauncher.scala:191)
14:20:22 	at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnitsSequential$3(GwenLauncher.scala:147)
14:20:22 	at scala.Option.map(Option.scala:146)
14:20:22 	at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnitsSequential$2(GwenLauncher.scala:147)
14:20:22 	at gwen.eval.GwenLauncher.evaluateUnit(GwenLauncher.scala:175)
14:20:22 	at gwen.eval.GwenLauncher.$anonfun$executeFeatureUnitsSequential$1(GwenLauncher.scala:143)
14:20:22 	at scala.collection.immutable.Stream.foldLeft(Stream.scala:545)
14:20:22 	at gwen.eval.GwenLauncher.executeFeatureUnitsSequential(GwenLauncher.scala:139)
14:20:22 	at gwen.eval.GwenLauncher.executeFeatureUnits(GwenLauncher.scala:99)
14:20:22 	at gwen.eval.GwenLauncher.run(GwenLauncher.scala:61)
14:20:22 	at gwen.eval.GwenApp.run(GwenApp.scala:55)
14:20:22 	at gwen.eval.GwenApp.delayedEndpoint$gwen$eval$GwenApp$1(GwenApp.scala:32)
14:20:22 	at gwen.eval.GwenApp$delayedInit$body.apply(GwenApp.scala:26)
14:20:22 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
14:20:22 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
14:20:22 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
14:20:22 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
14:20:22 	at scala.collection.immutable.List.foreach(List.scala:388)
14:20:22 	at scala.App.main(App.scala:76)
14:20:22 	at scala.App.main$(App.scala:74)
14:20:22 	at gwen.eval.GwenApp.main(GwenApp.scala:26)
14:20:22 	at gwen.web.WebInterpreter.main(WebIntepreter.scala)
14:20:22 Caused by: java.net.UnknownHostException: ip-10-0-1-100: Name or service not known
14:20:22 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
14:20:22 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
14:20:22 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
14:20:22 	at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
14:20:22 	... 29 more
14:20:22 Build step 'Execute shell' marked build as failure
14:20:24 Finished: FAILURE
`

**Comment by bjuric** [comment]
This has been fixed in gwen-web version 2.32.1. See: https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.32.1
