### ISSUE TITLE
Configure Custom Logging

### ISSUE THREAD

**Issue by priyankachaturvedi30** [gwen-interpreter/gwen#55]
I tried specifying my own logging using the below in gwen.properties file:
log4j.configuration={path_to_my_log4j.properties}
But I am still not able to generate the logs. Am I missing something?

**Comment by bjuric** [comment]
I can't see your path but if you're using backslashes, try changing them to forward slashes.

**Comment by bjuric** [comment]
Fixed in gwen-web v[2.42.1](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.42.1). Please close when ready @priyankachaturvedi30

**Comment by priyankachaturvedi30** [comment]
This works fine in latest Gwen-web v2.42.1. Verifed.
