### ISSUE TITLE
Issue with connecting to Postgres database

### ISSUE THREAD

**Issue by nsyal** [gwen-interpreter/gwen#56]
Hi,
In my feature files I have to run lot of queries to fetch data. I used ant job to run sql and its working fine in oracle labs.
However when I am trying to connect to postgres I have issue connectin

My db host is configured in environment files. And the build. xml I have provide the path fo postgres driver .
However its not picking up write environment and going to local host. 

Any suggestion on how can i resolve it and what is right way to troubleshoot it

**Comment by bjuric** [comment]
Hi @nsyal , Have you set up your DB settings in Gwen as per example here: https://gweninterpreter.wordpress.com/2017/02/13/sql-data-bindings-for-gwen/

Typically you would have an environment properties file that you pass to Gwen via the `-p` option. I'm assuming you had it working with Gwen in Oracle lab. Is that right? If not, I might need more details to help. The Gwen out log go console may also provide some clues.

**Comment by nsyal** [comment]
HI branko,

This is navdeep from pexa. Yes we had success with oracle. trying out with postgres. Is there a way i can contact you?
thanks

**Comment by bjuric** [comment]
@nsyal Maybe sign up to our dedicated support service at  gwenify.com if you're not comfortable posting more details here.

**Comment by nsyal** [comment]
hi @bjuric we did manage to resolve issue. it was in build.xml we have do some change .Yes i will sign up . thanks for your help
