### ISSUE TITLE
Doc Strings unavailable in .feature ?

### ISSUE THREAD

**Issue by dfriquet** [gwen-interpreter/gwen#60]
Hello Gwen!

I'm trying to figure out how to use DocStrings in `.feature` files. The [wiki states](https://github.com/gwen-interpreter/gwen/wiki/Doc-Strings):

> Every step in the Gwen DSL that includes a string literal parameter surrounded by quotes at the end of the step expression can now accept a Doc String value.

Unfortunately, I can't find any way to make it work. The simplest sample I can think of is the Google one, and I can't make it pass this way:

```gherkin
Feature: Google search

Scenario: Lucky Google search
    Given I have Google in my browser
     When I do a search for
      """
      Gwen automation
      """
     Then I should find a Gwen page
```

Gwen execution logs:

```
INFO - Evaluating Step: When I do a search for "Gwen automation"
ERROR - Failed step [at samples/google/Google.feature:6]: When I do a search for "Gwen automation": Unsupported or undefined step: When I do a search for "Gwen automation"
```

Did I make something wrong, or is it just available in `.meta` files?

Many thanks,
— David.

**Comment by bjuric** [comment]
Hi @dfriquet , DocStrings are currently only supported for the predefined [Web DSL steps](https://github.com/gwen-interpreter/gwen-web/wiki/Supported-DSL) and not custom StepDef's. We can certainly look to add support for them for StepDef's too. Will keep you posted.

**Comment by bjuric** [comment]
@dfriquet , We've managed to get something going..

![image](https://user-images.githubusercontent.com/1369994/123939544-940edf80-d9db-11eb-8ffd-a1df6049d2ee.png)

Note however, that if the docString spans multiple lines and is passed onto other nested steps, then there is a possibility that it could break the Gherkin step syntax. In such cases, Gwen will report an error. For example...

![image](https://user-images.githubusercontent.com/1369994/123939873-f667e000-d9db-11eb-888e-d4012c55a3ad.png)

So we need to be careful with how multiline DocStrings are used in nested steps.  

We will spend some time looking at other edge cases and test this more thoroughly before releasing. In the meantime, if any other breaking scenario comes to mind, please let us know.

**Comment by bjuric** [comment]
A general rule with regards to passing DocStrings as parameters to nested steps might have to be to only permit it if the parameter in the nested step is also defined in the DocString position (that is: at the end of the step and surrounded by quotes). In the negative example scenario above, the parameter in the nested step was not in that position.

**Comment by bjuric** [comment]
Will roll this out in next release.

**Comment by dfriquet** [comment]
That was fast, once again :tada: Thanks!

**Comment by bjuric** [comment]
@dfriquet, released in gwen-web v[2.53.0](https://github.com/gwen-interpreter/gwen-web/releases/tag/v2.53.0)

**Comment by bjuric** [comment]
@dfriquet have you tried it?

**Comment by bjuric** [comment]
Fix released. Closing issue.
